### ISSUE TITLE
.fswiki 拡張子のサポート要望

### ISSUE THREAD

**Issue by jfut** [entooone/freestylewiki-vscode#2]
https://github.com/entooone/freestylewiki-vscode/blob/abf57c51eba682e0d85c8872054ac4eeed7b23be/package.json#L30-L32

この拡張機能はデフォルトでは拡張子が `.fsw` を対象に実装されていますが、可能であれば `.fswiki` のサポートを希望します。

理由としては、まず FreeStyle Wiki の `data/` 以下のデータでは、`FrontPage.wiki` のように `.wiki` が使用されています。
さすがに `.wiki` を対象としてしまうと、一般名称過ぎて好ましくないと思われるため、FreeStyle Wiki のプロジェクトサイト URL にも使われている `fswiki` を使用した `.fswiki` の方が利用者によって判りやすいと思うからです。

ご検討の程よろしくお願いいたします。

**Comment by entooone** [comment]
ご提案ありがとうございます。 `.fswiki` にも対応したいと思います。

**Comment by jfut** [comment]
ありがとうございます！

**Comment by entooone** [comment]
これから、Marketplace の方も更新します。

**Comment by entooone** [comment]
Marketplace の方も更新しました。

**Comment by jfut** [comment]
ありがとうございます！Marketplace からアップデートして拡張子 `.fswiki` で動作することを確認しました。
