### ISSUE TITLE
編集領域で見出しの折りたたみと展開のサポート

### ISSUE THREAD

**Issue by jfut** [entooone/freestylewiki-vscode#22]
編集領域で見出しの折りたたみと展開ができると嬉しいです。

- https://code.visualstudio.com/docs/editor/codebasics#_folding
- https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding

ご検討の程よろしくお願いいたします。

**Comment by entooone** [comment]
ご提案ありがとうございます。

https://github.com/entooone/freestylewiki-vscode/commit/727095d67ab9d22179c20f0f107032344ad3ba44 で見出し・ブロックプラグインの展開・折りたたみに対応しました。

最新バージョンに更新いただくことで利用できるようになると思います。ご確認お願いいたします。
https://marketplace.visualstudio.com/items?itemName=entooone.freestylewiki-extension

**Comment by jfut** [comment]
素早く対応していただきありがとうございます！

期待どおりに展開・折りたたみできることを確認しました。細かい点で要望です。

折りたたんだ時に、次の見出しの前に空行がある場合は、その空行を残しておいて欲しいです。これは長い見出しブロックを折りたたんでまとめて削除や切り取る際に空行が残っていると編集がしやすいメリットがあります。

- 現在の折りたたみ前

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/7c793455-1b14-48d1-b525-35947dc51a1a)

- 現在の折りたたみ後

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/b257e4f6-9a88-4109-a51a-d7f8b3df8877)

YAML ファイルの折りたたみではそのようになっていました。

- YAML ファイルの折りたたみ前

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/b69eb773-89f6-42c7-9b07-90987f3892f0)

- YAML ファイルの折りたたみ後

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/9a1af72b-a400-45df-9b62-01c6971f5a52)

**Comment by entooone** [comment]
早速のご確認ありがとうございます。

Markdown の拡張機能なども空行を考慮しているようですね。
https://github.com/entooone/freestylewiki-vscode/commit/77c99421bcaacc88c4d6c290807329217ae4d478 で挙動を修正しました。

最新バージョンに修正を適用済みです。

**Comment by jfut** [comment]
@entooone 
ありがとうございます。完璧に期待どおりになりました！
