### ISSUE TITLE
テーブル記法フォーマット時の左寄せ

### ISSUE THREAD

**Issue by jfut** [entooone/freestylewiki-vscode#23]
[go-fswiki](https://github.com/entooone/go-fswiki) の方の挙動だと思いますが、フォーマッターでテーブル記法を整形すると下図のように右寄せになります。

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/66b1cc88-226c-4bbf-bc9b-41339a6b3080)

これは、下図のように左寄せの方が自然な感じがしますが意図的なものでしょうか？

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/5686c706-213e-4d57-94aa-625f5a84fa8b)

また、これは好みになってしまいますが上図のように 2 列名以降の区切り文字 `,` の前にはスペースが 1 個あると見やすく、オプション設定でも良いのでカスタマイズできると嬉しいです。

参考までに、Markdown のフォーマッターのデフォルトは左寄せでした。

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/33bbec37-c654-4971-ad80-4803cce7738d)

**Comment by entooone** [comment]
ご提案ありがとうございます。

右寄せにした強い理由はないですね。オプションで左寄せ・右寄せが選択できるようにしたいと思います。右寄せへのこだわりはないので、markdown に合わせてデフォルトも左寄せにします。

> これは好みになってしまいますが上図のように 2 列名以降の区切り文字 , の前にはスペースが 1 個あると見やすく、オプション設定でも良いのでカスタマイズできると嬉しいです。

こちらについてもオプション追加したいと思います。

**Comment by jfut** [comment]
ご検討ありがとうございます。大変助かります。

**Comment by entooone** [comment]
こちらのオプションを実装いたしました。また、デフォルト値を左寄せ・末尾スペース挿入にしました。  
https://github.com/entooone/freestylewiki-vscode/releases/tag/v0.8.0

最新バージョンのご確認をお願いいたします。

**Comment by jfut** [comment]
@entooone 毎度ありがとうございます！

試してみて、基本的に理想どおりなのですが、細かい点で下図のように一番右のセルの末尾の空白は削除されているのがより理想です。

![image](https://github.com/entooone/freestylewiki-vscode/assets/128867/3c70ccf5-9c9c-4d49-bb03-440c82892202)

背景としては、エディタでよく末尾の空白ペースを保存時に削除するオプションがあり、VS Code だと `vscode files.trimTrailingWhitespace` オプションが該当し、このオプションが有効の場合に相性が悪いです。末尾の空白が付与されなければ、`vscode files.trimTrailingWhitespace` オプションの設定が有効・無効どちらでも影響無くなるため好ましいです。

**Comment by entooone** [comment]
ご確認ありがとうございます。修正いたしました。
再度、最新バージョンで動作のご確認をお願いいたします。

**Comment by jfut** [comment]
@entooone 期待する完璧な動作になりました！！
一連のご修正ありがとうございます。
