### ISSUE TITLE
対象とする拡張子の説明の追加

### ISSUE THREAD

**Issue by jfut** [entooone/freestylewiki-vscode#3]
この拡張機能が対象とする拡張子の説明がどこにもないようです。

インストールした利用者がすぐに機能を理解できるように、[README.md](https://github.com/entooone/freestylewiki-vscode/blob/master/README.md) や [拡張機能ページ](https://marketplace.visualstudio.com/items?itemName=entooone.freestylewiki-extension) に対象とする拡張子の説明があるとより良いと思います。

**Comment by entooone** [comment]
ご指摘ありがとうございます。 対応する拡張子の一覧を `README.md` に追加します。
