### ISSUE TITLE
拡張子 ".wiki" への対応

### ISSUE THREAD

**Issue by tetlabo** [entooone/freestylewiki-vscode#7]
長年FSWikiを使っていて、何かエディタから手軽に更新できるツールがないか探していました。とても便利な拡張をありがとうございます。

FSWiki (3.6.5) で、Webインターフェースから作成される新しい記事は、".wiki" の拡張子になっているので、こちらにも対応いただけるとうれしいです。

**Comment by entooone** [comment]
ご提案ありがとうございます。

`.wiki` は FreeStyle Wiki に限らない、一般的な名称のため、他の拡張機能と衝突する可能性が考えられます。そのため、本拡張機能では `.wiki` に対応していません。

ユーザ側で設定していただければと思っています。
既にご存知かもしれませんが、VSCode の `settings.json` に下記の設定を追加することで `.wiki` に本拡張機能を永続的に適用することができます。

```
{
    // 中略
    "files.associations": {
        "*.wiki": "fsw"
    }
}
```

参考: https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language

こちらのような方法ではいかがでしょうか？

よろしくお願いします。

**Comment by tetlabo** [comment]
ありがとうございます。手元では、そのように設定して使用し始めました。VSCodeのRemote-SSH拡張と組み合わせて、Webサーバ上の文書を、使い慣れたエディタで編集できるのはとても便利です。今後ともよろしくお願いいたします。
